import Head from 'next/head'

import About from './components/About'
import Main from './components/Main'
import Rent from './components/Rent'

export default function Home() {
  return (
    <div>
     <Head>
       <title>Arinze|Full Stack Developer</title>
       <meta name="description" content="generated by next app "/>
       {/* <link rel="icon" href="/favicon.ico"/> */}
     </Head>
     <Main/>
     <Rent/>
     <About/>
    </div>
  )
}
